default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: "postgres"
  password: "Biotrack1!"
  host: 127.0.0.1
  port: 5432
  database: "biotrackthc"

test:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: "postgres"
  password: "Biotrack1!"
  host: 127.0.0.1
  port: 5432
  database: "biotrackthc"

production:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: "postgres"
  host: "127.0.0.1"
  port: "5432"
  database: "biotrackthc"
  password: <%= ENV['BIOTRACK_DATABASE_PASSWORD'] %>